import { assetPath } from "@/lib/assetPath";
import Image from "next/image";

const workflow = [
  {
    eyebrow: "Brand foundation",
    title: "One visual system across the public product",
    body: "The wellness experience establishes the typography, peach palette, tone, and interaction patterns that the content tools reuse. The goal was to make generated media feel like part of the same product rather than a disconnected template export.",
    src: "/projects/spiritual-peach/spiritual-peach-wellness-platform-homepage.png",
    alt: "Spiritual Peach wellness platform homepage with a soft peach visual identity",
    width: 1246,
    height: 712,
  },
  {
    eyebrow: "Reusable content",
    title: "Turn product moments into shareable assets",
    body: "Oracle readings can be saved or shared as images and animated GIFs. That same idea became the foundation for a broader content system: structured copy and branded presentation that can move between the product and social channels.",
    src: "/projects/spiritual-peach/spiritual-peach-oracle-card-reading-share-workflow.png",
    alt: "Spiritual Peach oracle reading with controls to share or export the result as an image or GIF",
    width: 1035,
    height: 824,
  },
  {
    eyebrow: "CMS-style workflow",
    title: "Peach Studio organizes content before generation",
    body: "The local admin experience separates content management from presentation. Content sets can be created, edited, reordered, and reused, while dedicated generators turn those structured items into social posts, stories, Pinterest pins, and short-form video.",
    src: "/projects/spiritual-peach/peach-studio-branded-content-cms-dashboard.png",
    alt: "Peach Studio admin dashboard for managing content sets, social generation, and reels",
    width: 1221,
    height: 868,
  },
  {
    eyebrow: "Automated production",
    title: "Preview and export without rebuilding the design",
    body: "The generator combines saved or custom content with an uploaded background and branded overlays. A live preview makes the output visible before export, reducing repetitive layout work while keeping the visual system consistent.",
    src: "/projects/spiritual-peach/peach-studio-social-media-reel-generator.png",
    alt: "Peach Studio reel generator with content controls and a branded vertical video preview",
    width: 1319,
    height: 827,
  },
];

const outputs = [
  {
    src: "/projects/spiritual-peach/butterfly-hug-instagram-story-branded-content.png",
    alt: "Butterfly Hug branded Instagram Story generated by Peach Studio",
    width: 1080,
    height: 1920,
    label: "Instagram Story",
  },
  {
    src: "/projects/spiritual-peach/butterfly-hug-instagram-portrait-branded-content.png",
    alt: "Butterfly Hug branded Instagram portrait post generated by Peach Studio",
    width: 1080,
    height: 1350,
    label: "Instagram portrait",
  },
  {
    src: "/projects/spiritual-peach/butterfly-hug-pinterest-branded-content.png",
    alt: "Butterfly Hug branded Pinterest pin generated by Peach Studio",
    width: 1000,
    height: 1500,
    label: "Pinterest pin",
  },
];

export default function SpiritualPeachEvidence() {
  return (
    <section aria-labelledby="spiritual-peach-content-system">
      <p className="text-sm font-medium uppercase tracking-[0.24em] text-orange-300">
        Product case study
      </p>
      <h2
        id="spiritual-peach-content-system"
        className="mt-3 text-3xl font-semibold tracking-tight text-white"
      >
        Building a branded content system, not just individual posts
      </h2>
      <p className="mt-4 text-lg leading-8 text-slate-300">
        I approached content creation like a small CMS: store the meaning and
        structure once, then apply consistent brand rules when adapting it for
        each social format. This made it possible to create a coordinated
        campaign without manually rebuilding every asset.
      </p>

      <div className="mt-9 space-y-8">
        {workflow.map((item) => (
          <article
            key={item.title}
            className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.035]"
          >
            <div className="p-5 md:p-6">
              <p className="text-xs font-medium uppercase tracking-[0.2em] text-orange-200">
                {item.eyebrow}
              </p>
              <h3 className="mt-2 text-xl font-semibold text-white">{item.title}</h3>
              <p className="mt-3 text-sm leading-7 text-slate-300">{item.body}</p>
            </div>
            <div className="border-t border-white/10 bg-[#fbf6f2]">
              <Image
                src={assetPath(item.src)}
                alt={item.alt}
                width={item.width}
                height={item.height}
                sizes="(min-width: 1024px) 768px, 100vw"
                className="h-auto w-full"
              />
            </div>
          </article>
        ))}
      </div>

      <div className="mt-10">
        <h3 className="text-2xl font-semibold text-white">Generated campaign outputs</h3>
        <p className="mt-3 text-base leading-7 text-slate-300">
          One Butterfly Hug content set adapted across channel-specific aspect
          ratios while preserving typography, framing, color, and attribution.
        </p>
        <div className="mt-6 grid gap-5 sm:grid-cols-3 sm:items-start">
          {outputs.map((output) => (
            <figure
              key={output.src}
              className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.035]"
            >
              <Image
                src={assetPath(output.src)}
                alt={output.alt}
                width={output.width}
                height={output.height}
                sizes="(min-width: 640px) 240px, 100vw"
                className="h-auto w-full"
              />
              <figcaption className="px-4 py-3 text-sm text-slate-300">
                {output.label}
              </figcaption>
            </figure>
          ))}
        </div>
      </div>
    </section>
  );
}
